In [2]:
!pip install pandas openpyxl


import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


import warnings

Requirement already satisfied: pandas in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: openpyxl in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (3.0.10)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: et_xmlfile in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
# 1.Load the dataset and explore the variables.

data = pd.read_csv("/Users/elnazshahzeidi/Downloads/customer_churn.csv")
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
data['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [5]:
data.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
data1 = pd.get_dummies(data, columns=['Churn'], drop_first=True)

data1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn_Yes
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,False
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,False
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,True
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,False
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,False
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,False
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,False
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,True
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,False

In [7]:
# 3,4. Extract the target and independent variables

y = data1['Churn_Yes']
X = data1[['tenure', 'SeniorCitizen', 'MonthlyCharges']]

In [8]:
# 5.Scale the independent variables
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)


# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [9]:
# Build the model
classification = LogisticRegression()

classification.fit(X_train, y_train)



# 6.Make predictions and Evaluate them.
predictions = classification.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

       False       0.82      0.92      0.87      1539
        True       0.68      0.45      0.54       574

    accuracy                           0.79      2113
   macro avg       0.75      0.69      0.70      2113
weighted avg       0.78      0.79      0.78      2113

In [10]:
# 7.Reason of Achieve 70% Accuracy : Class Imbalance

In [11]:
# 8. Oversampling - Apply SMOTE
!pip install scikit-learn imbalanced-learn pandas
from imblearn.over_sampling import SMOTE


y = data1['Churn_Yes']
X = data1[['tenure', 'SeniorCitizen', 'MonthlyCharges']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

smote = SMOTE()
X_train, y_train = smote.fit_resample(X_train, y_train)
y_train.value_counts()

Requirement already satisfied: scikit-learn in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (1.5.2)
Requirement already satisfied: imbalanced-learn in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (0.12.3)
Requirement already satisfied: pandas in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: numpy>=1.19.5 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.6.0 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/elnazshahzeidi/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

Churn_Yes
False    4139
True     4139
Name: count, dtype: int64

In [12]:
y_test.value_counts()

Churn_Yes
False    1035
True      374
Name: count, dtype: int64

In [13]:
classification = LogisticRegression(random_state=42, max_iter=100000)
classification.fit(X_train, y_train)

predictions = classification.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

       False       0.88      0.72      0.79      1035
        True       0.48      0.72      0.57       374

    accuracy                           0.72      1409
   macro avg       0.68      0.72      0.68      1409
weighted avg       0.77      0.72      0.73      1409

In [17]:
# 9. Tomek Links

from imblearn.under_sampling import TomekLinks



tomek = TomekLinks()
X_tomek, y_tomek = tomek.fit_resample(X_scaled, y)

# Split the Tomek dataset
X_train_tomek, X_test_tomek, y_train_tomek, y_test_tomek = train_test_split(X_tomek, y_tomek, test_size=0.3, random_state=42)

# Build and evaluate the model
model_tomek = LogisticRegression()
model_tomek.fit(X_train_tomek, y_train_tomek)

# Make predictions
y_pred_tomek = model_tomek.predict(X_test_tomek)

# Evaluate the model

print(classification_report(y_test_tomek, y_pred_tomek))

              precision    recall  f1-score   support

       False       0.83      0.91      0.87      1409
        True       0.70      0.51      0.59       560

    accuracy                           0.80      1969
   macro avg       0.76      0.71      0.73      1969
weighted avg       0.79      0.80      0.79      1969